// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://iicpenjyceznvkitrivp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlpY3Blbmp5Y2V6bnZraXRyaXZwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA2NjI5ODYsImV4cCI6MjA2NjIzODk4Nn0.6htEtbj0rUZKX7tgHvmqcukFZNLlBr8WalU51dqX0l8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);